name: pay
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  image_picker: ^1.0.8
  qr_flutter: ^4.1.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  path_provider: ^2.1.3
  sqflite: ^2.3.2
  firebase_storage: ^11.6.0
  qr_code_scanner: ^1.0.1
  firebase_app_check: ^0.2.1+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
